
### POST /api/v1/tenants
POST http://localhost:8081/tenants/provision
Content-Type: application/json

{
  "id": "04a9bce7-b1bd-4e00-b7ff-1fb4a5c06bbe",
  "tenantName": "string",
  "tenantDescription": "string",
  "administorFirstName": "string",
  "administorLastName": "string",
  "emailAddress": "prueba@gmail.com",
  "primaryTelephone": "123-456-7880",
  "secondaryTelephone": "123-456-7890",
  "addressStreetAddress": "calle easo",
  "addressCity": "random city",
  "addressStateProvince": "random state",
  "addressPostalCode": "20180",
  "addressCountryCode": "US"
}

<> 2024-10-02T213934.201.txt
<> 2024-10-02T213807.400.txt
<> 2024-10-02T213756.400.txt