###
POST http://{{host}}/api/web/ian/forecast/generate-default
X-Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlkIjoxLCJzY29wZXMiOlsiUk9MRV9EQVRBIiwiUk9MRV9BRE1JTiIsIlJPTEVfU1VQRVJBRE1JTiIsIlJPTEVfWEFCRVQiXSwianRpIjoiN2M5N2U4ZGEtY2NkYy00YTM4LTgzOTEtNjY3ODgwNzViZDJkIiwiaXNzIjoieGFiZXQubmV0IiwiaWF0IjoxNzM3NTUyMTg0LCJleHAiOjE3Mzc1NTMwODR9.hEXOWCBtRSCp7VrVyRohwPmE2ZNLa1kJQms8gTBve6BE9xmvevqC_FqylgOCOc26uLKGrmr7qhY2S6y1Uz-AbQ

<> 2025-01-22T143655.401.txt
