### Get pending registration lack
POST https://pruebas-ian.dwall.xabet.net/gross-margin/pending-registration-lack
X-Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlkIjoxLCJzY29wZXMiOlsiUk9MRV9EQVRBIiwiUk9MRV9BRE1JTiIsIlJPTEVfU1VQRVJBRE1JTiIsIlJPTEVfWEFCRVQiXSwianRpIjoiNmUzNDI3YzMtZmZlNi00MWNhLTg2MWEtZGQ4M2QxNzAzZDNkIiwiaXNzIjoieGFiZXQubmV0IiwiaWF0IjoxNzI3ODg3NDk5LCJleHAiOjE3Mjc4ODgzOTl9.EYGZKcrT0_XXbjtfbEuDTCMYZzOLKv4RwbUb-M-2v_cZFlmqXsP07QYjkczyBHfON6kyexPw9bj76XTjRh75vw

<> 2024-10-02T185206.200.html
<> 2024-10-02T184734.200.html

### Calculate all gross margins
POST https://pruebas-ian.dwall.xabet.net/gross-margin/calculateAllGrossMargins
X-Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlkIjoxLCJzY29wZXMiOlsiUk9MRV9EQVRBIiwiUk9MRV9BRE1JTiIsIlJPTEVfU1VQRVJBRE1JTiIsIlJPTEVfWEFCRVQiXSwianRpIjoiNmUzNDI3YzMtZmZlNi00MWNhLTg2MWEtZGQ4M2QxNzAzZDNkIiwiaXNzIjoieGFiZXQubmV0IiwiaWF0IjoxNzI3ODg3NDk5LCJleHAiOjE3Mjc4ODgzOTl9.EYGZKcrT0_XXbjtfbEuDTCMYZzOLKv4RwbUb-M-2v_cZFlmqXsP07QYjkczyBHfON6kyexPw9bj76XTjRh75vw

<> 2024-10-02T185208.200.html
