openapi: "3.1.0"
info:
  title: "distributed_portfolio API"
  description: "distributed_portfolio API"
  version: "1.0.0"
servers:
  - url: "https://distributed_portfolio"
paths:
  /groups/provision:
    post:
      summary: "POST groups/provision"
      operationId: "provisionGroup"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProvisionGroupCommand"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Void"
components:
  schemas:
    ProvisionGroupCommand:
      type: "object"
      properties:
        id:
          type: "string"
        description:
          type: "string"
        groupName:
          type: "string"
        tenantId:
          type: "string"
    Void:
      type: "object"
      properties: { }