openapi: "3.1.0"
info:
  title: "distributed_portfolio API"
  description: "distributed_portfolio API"
  version: "1.0.0"
servers:
  - url: "https://localhost:8081"
tags:
  - name: "Tenants"
    description: "Tenant management"
paths:
  /tenants/provision:
    post:
      summary: "Tenants Provision"
      description: "Provision a new tenant"
      operationId: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProvisionTenantCommand"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
components:
  schemas:
    ProvisionTenantCommand:
      type: "object"
      properties:
        id:
          type: "string"
        tenantName:
          type: "string"
        tenantDescription:
          type: "string"
        administorFirstName:
          type: "string"
        administorLastName:
          type: "string"
        emailAddress:
          type: "string"
        primaryTelephone:
          type: "string"
        secondaryTelephone:
          type: "string"
        addressStreetAddress:
          type: "string"
        addressCity:
          type: "string"
        addressStateProvince:
          type: "string"
        addressPostalCode:
          type: "string"
        addressCountryCode:
          type: "string"
      example:
        id: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        tenantName: "Acme Corp"
        tenantDescription: "Descripción del tenant Acme Corp"
        administorFirstName: "Juan"
        administorLastName: "Pérez"
        emailAddress: "juan.perez@ejemplo.com"
        primaryTelephone: "(123)456-7880"
        secondaryTelephone: "123-456-7890"
        addressStreetAddress: "123 Calle Principal"
        addressCity: "Ciudad Ejemplo"
        addressStateProvince: "CA"
        addressPostalCode: "12345"
        addressCountryCode: "US"